### ISSUE TITLE
rename only selected instance

### ISSUE THREAD

**Issue by studiostoll** [sonburn/symbol-instance-renamer#1]
love this plugin! :-) have you ever considered giving an option to only rename the symbol instance that's currently selected?

use case: we often rename symbol instances intentionally to keep them short and crisp for nested symbol overrides. right now, these always get updated…

**Comment by sonburn** [comment]
Not a bad idea. I wouldn't want to give this plugin any UI as it works best as a command, however, I could add a variation of the command to only update the selected instance. I will explore this further, thanks for the idea.

**Comment by studiostoll** [comment]
@sonburn yeah, no UI! thanks for investigating :-)

**Comment by sonburn** [comment]
I just published an update, give it a shot and let me know how it works for you. I could probably do more, like if the user selects a symbol master, rename all the instances for that master only... but this is a start.

**Comment by rodnem** [comment]
Great update !

**Comment by sonburn** [comment]
I'll go ahead and close this issue, thanks for the feedback!
