### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by phil-lgr** [sonburn/symbol-instance-renamer#10]
I have OCD (we all have it lol) and this Sketch plugin restored my sanity, thank you. BTW I would have gladly dropped $10 for this nice little thing. 👍

**Comment by sonburn** [comment]
@phil-lgr Thank you for the feedback, I am always happy to hear that my plugins benefit others and not just me. Since you said it, there _is_ a donate link within the menu of each of my plugins. 🙂 Anything is always appreciated, even this feedback, so thank you.

**Comment by phil-lgr** [comment]
✅ done, thank you

**Comment by sonburn** [comment]
@phil-lgr Thank you for your generosity!
