### ISSUE TITLE
Doesn't update to 2.9 in Sketch Runner in Sketch 72.1

### ISSUE THREAD

**Issue by F-DK** [sonburn/symbol-instance-renamer#16]
2.9 is displayed as available and ready to update in Sketch Runner but update is not possible.
<img width="632" alt="Screen Shot 2021-05-12 at 11 34 42" src="https://user-images.githubusercontent.com/1479114/117953095-19e4a780-b316-11eb-987d-f952523b255a.png">

**Comment by Tafkadasoh** [comment]
I have the same issue. Looks like @sonburn forgot to update the version inside [manifest.json](https://github.com/sonburn/symbol-instance-renamer/blob/master/Symbol%20Instance%20Renamer.sketchplugin/Contents/Sketch/manifest.json).

**Comment by F-DK** [comment]
@Tafkadasoh You're right. That's still at 2.8.

**Comment by sonburn** [comment]
@F-DK, @Tafkadasoh, thanks guys, should be fixed now. Sorry for the annoyance!

**Comment by Tafkadasoh** [comment]
@sonburn Thank you for the quick resolution
