### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by pterisaur** [sonburn/symbol-instance-renamer#3]
This is a very useful tool, thank you! 

One thing I'm frequently finding myself doing: selecting all instances on a page and renaming them. I do this instead of "Rename All Instances" because I generally don't want to rename instances for nested symbols on the Symbols page. My suggestion is to add one or more of these actions:

- Rename All Instances on Current Page
- Rename All Instances, Excluding the Symbols Page

**Comment by sonburn** [comment]
@pterisaur Sorry for not responding sooner, this little plugin doesn't get much love compared to Symbol Organizer. Glad you find it useful though!

I just added a new function to the plugin (version 2.2), to rename all instances on the current page. I'll consider the "all pages but symbols page" idea for a future enhancement, but this should get you a step closer. I also optimized the code quite a bit (should be much snappier), and added appcast support so you should be made aware of future updates from within Sketch itself.

Thank you for your support and feedback!

**Comment by sonburn** [comment]
Ok fine, I added another function to do all pages, except symbols page (v2.3)... happy now?! 😉

It was easy and I had to publish a fix for something else anyway, thanks again for the suggestions.
