### ISSUE TITLE
Feature Request: Rename All Instances in Selected Artboards

### ISSUE THREAD

**Issue by lucaorio** [sonburn/symbol-instance-renamer#7]
👆 This would be great!

**Comment by fbmore** [comment]
@lucaorio the plugin Rename it already allows renaming of selected artboards. Tried it?

**Comment by lucaorio** [comment]
@fbmore Rename It is great, but it doesn't necessarily address this use case (at least not in an automatic way, which is the purpose of symbol-instance-renamer).

I'm looking to reset the layer name of all the instances of one/multiple symbols, just on selected artboards.

**Comment by sonburn** [comment]
@lucaorio I think I understand the request, something like "Rename All Instances in Selected Artboard(s)"?

**Comment by lucaorio** [comment]
@sonburn Correct! I don't remember the specific use case, right now. But a month ago I found myself wondering "hey, this would really make a difference in this case scenario" 😀

**Comment by sonburn** [comment]
@lucaorio Makes sense, working on an update now in fact as I needed to make another update. Stay tuned...

**Comment by lucaorio** [comment]
@sonburn Thanks, Jason! And keep up the good work, I'm using some of your plugins on a daily basis :)

**Comment by fbmore** [comment]
@lucaorio I was confused by “all selected artboards” as I thought you wanted to rename the selected artboards, not the symbol instances in the selected artboards. Makes sense now.

**Comment by sonburn** [comment]
@lucaorio Check out version 2.5 which I just published, it contains this new functionality.

**Comment by lucaorio** [comment]
@sonburn It works perfectly! I just changed the issue title for discoverability, and I'm also going to close it. Thanks for taking care of this 👍
